name: Deploy to Firebase Hosting on main branch push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Verify firebase.json exists
        uses: andstor/file-existence-action@v3
        with:
          file: 'firebase.json'

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUN }}'
          channelId: live
          projectId: ai-agent-9f171
